name: CI

on: 
  push:
    branches: [ "main" ]

jobs: 
  execute-unit-test:
    runs-on: ubuntu-latest  # OBLIGATOIRE : Définit l'OS (souvent Linux)
    defaults:
      run:
        working-directory: order-service
    
    steps:  # OBLIGATOIRE : Pour lister les commandes
      
      # Étape 1 : Récupérer le code (sinon le dossier est vide)
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Installer Java (Recommandé pour Maven)
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      # Étape 3 : Installer les dépendances (sans lancer les tests tout de suite)
      - name: Install dependencies
        run: mvn install -DskipTests

      # Étape 4 : Tests unitaires
      - name: Run Unit Tests
        run: mvn test -Dtest=PricingServiceTest

  execute-integ-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: order-service
    needs: execute-unit-test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      # Maintenant vous pouvez lancer le test
      - name: Run Integration Tests
        run: mvn test -Dtest=PricingIntegrationTest,PasswordPolicyTest